version: '3.3'

services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=jfbarahonag
      - MYSQL_PASSWORD=adminjfbg
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql